"use server";

import { auth, currentUser } from "@clerk/nextjs/server";
import { revalidatePath } from "next/cache";
import { createClient } from "@/utils/supabase/server";
import type { Article, ArticleFormData, ArticleStatus } from "./types";

/**
 * Ensures the caller is an authenticated administrator.
 */
async function verifyAdminAuth(): Promise<string> {
  const { userId, sessionClaims } = await auth();

  if (!userId) {
    throw new Error("Unauthorized: Authentication required.");
  }

  const role = sessionClaims?.metadata?.role;
  if (role !== "admin") {
    throw new Error("Forbidden: Administrator privileges required.");
  }

  return userId;
}

interface ArticleDbRow {
  id: string;
  slug: string;
  title_en: string;
  title_ar: string;
  excerpt_en: string | null;
  excerpt_ar: string | null;
  content_html_en: string | null;
  content_html_ar: string | null;
  content_en?: unknown;
  content_ar?: unknown;
  cover_image: string | null;
  category: string;
  category_slug: string;
  tags: string[] | null;
  layout_variant: string;
  status: string;
  read_time_en: string | null;
  read_time_ar: string | null;
  author_name: string;
  author_role: string | null;
  author_avatar: string | null;
  published_at: string | null;
  created_at: string;
  updated_at: string;
  created_by?: string | null;
}

function mapRowToArticle(row: ArticleDbRow): Article {
  return {
    id: row.id,
    slug: row.slug,
    titleEn: row.title_en,
    titleAr: row.title_ar,
    excerptEn: row.excerpt_en || "",
    excerptAr: row.excerpt_ar || "",
    contentHtmlEn: row.content_html_en || "",
    contentHtmlAr: row.content_html_ar || "",
    contentEn: row.content_en,
    contentAr: row.content_ar,
    coverImage: row.cover_image || undefined,
    category: row.category,
    categorySlug: row.category_slug,
    tags: row.tags || [],
    layoutVariant: (row.layout_variant as Article["layoutVariant"]) || "default",
    status: (row.status as ArticleStatus) || "draft",
    readTimeEn: row.read_time_en || "5 min read",
    readTimeAr: row.read_time_ar || "5 دقائق للقراءة",
    authorName: row.author_name || "Admin",
    authorRole: row.author_role || "Administrator",
    authorAvatar: row.author_avatar || undefined,
    publishedAt: row.published_at || undefined,
    createdAt: row.created_at,
    updatedAt: row.updated_at,
    createdBy: row.created_by || undefined,
  };
}

/**
 * Retrieves all articles directly from database (with optional status filter).
 */
export async function getArticlesAction(statusFilter?: ArticleStatus): Promise<Article[]> {
  try {
    const supabase = await createClient();
    let query = supabase.from("articles").select("*").order("created_at", { ascending: false });

    if (statusFilter) {
      query = query.eq("status", statusFilter);
    }

    const { data, error } = await query;

    if (!error && data) {
      return (data as unknown as ArticleDbRow[]).map(mapRowToArticle);
    }
    if (error) {
      console.error("Supabase getArticlesAction error:", error.message);
    }
  } catch (err) {
    console.error("Supabase getArticlesAction exception:", err);
  }

  return [];
}

/**
 * Retrieves a single article by slug directly from database.
 */
export async function getArticleBySlugAction(slug: string): Promise<Article | null> {
  try {
    const supabase = await createClient();
    const { data, error } = await supabase
      .from("articles")
      .select("*")
      .eq("slug", slug)
      .maybeSingle();

    if (!error && data) {
      return mapRowToArticle(data as unknown as ArticleDbRow);
    }
    if (error) {
      console.error("Supabase getArticleBySlugAction error:", error.message);
    }
  } catch (err) {
    console.error("Supabase getArticleBySlugAction exception:", err);
  }

  return null;
}

/**
 * Saves or updates an article in Supabase with author automatically resolved from Clerk.
 * - For new articles (INSERT): IDs, created_at, and updated_at are NOT generated by frontend;
 *   Supabase automatically sets id via gen_random_uuid(), created_at via DEFAULT NOW(),
 *   and updated_at via DEFAULT NOW().
 * - For existing articles (UPDATE): updated_at is NOT passed; the database trigger
 *   'set_articles_updated_at' automatically updates updated_at on every update.
 */
export async function saveArticleAction(
  formData: ArticleFormData
): Promise<{ success: boolean; article?: Article; error?: string }> {
  try {
    const user = await currentUser();
    const adminId = user?.id || (await verifyAdminAuth());

    // Automatically resolve author name, avatar and role from the current Clerk user
    const authorName =
      user?.fullName ||
      [user?.firstName, user?.lastName].filter(Boolean).join(" ") ||
      user?.username ||
      user?.primaryEmailAddress?.emailAddress ||
      "Administrator";

    const authorAvatar = user?.imageUrl || undefined;
    const authorRole = (user?.publicMetadata?.role as string) || "Administrator";

    // Generate slug from title if empty
    const cleanSlug = (formData.slug || formData.titleEn)
      .toLowerCase()
      .trim()
      .replace(/[^\w\s-]/g, "")
      .replace(/[\s_-]+/g, "-")
      .replace(/^-+|-+$/g, "");

    const categorySlug = (formData.category || "engineering").toLowerCase().replace(/\s+/g, "-");

    // Auto-calculate read time if not provided
    const words = formData.contentHtmlEn.replace(/<[^>]+>/g, " ").split(/\s+/).filter(Boolean).length;
    const calcMinutes = Math.max(1, Math.ceil(words / 200));
    const readTimeEn = formData.readTimeEn || `${calcMinutes} min read`;
    const readTimeAr = formData.readTimeAr || `${calcMinutes} دقائق للقراءة`;

    const baseRow = {
      slug: cleanSlug,
      title_en: formData.titleEn,
      title_ar: formData.titleAr,
      excerpt_en: formData.excerptEn || null,
      excerpt_ar: formData.excerptAr || null,
      content_html_en: formData.contentHtmlEn || null,
      content_html_ar: formData.contentHtmlAr || null,
      cover_image: formData.coverImage || null,
      category: formData.category || "Engineering",
      category_slug: categorySlug,
      tags: formData.tags || [],
      layout_variant: formData.layoutVariant || "default",
      status: formData.status || "draft",
      read_time_en: readTimeEn,
      read_time_ar: readTimeAr,
      author_name: authorName,
      author_role: authorRole,
      author_avatar: authorAvatar || null,
      created_by: adminId,
    };

    const supabase = await createClient();
    let savedRow: ArticleDbRow;

    if (formData.id) {
      // UPDATE: Only update content fields. Do NOT send id, created_at, or updated_at.
      // Database trigger automatically sets updated_at = NOW()!
      const updatePayload: Record<string, unknown> = {
        ...baseRow,
      };
      if (formData.status === "published") {
        updatePayload.published_at = new Date().toISOString();
      }

      const { data, error: updateError } = await supabase
        .from("articles")
        .update(updatePayload)
        .eq("id", formData.id)
        .select()
        .single();

      if (updateError || !data) {
        console.error("Supabase update error:", updateError);
        return { success: false, error: updateError?.message || "Failed to update article." };
      }
      savedRow = data as unknown as ArticleDbRow;
    } else {
      // INSERT: Never pass id, created_at, or updated_at.
      // Supabase automatically generates id via gen_random_uuid(), created_at via DEFAULT NOW(),
      // and updated_at via DEFAULT NOW()!
      const insertPayload: Record<string, unknown> = {
        ...baseRow,
        published_at: formData.status === "published" ? new Date().toISOString() : null,
      };

      const { data, error: insertError } = await supabase
        .from("articles")
        .insert(insertPayload)
        .select()
        .single();

      if (insertError || !data) {
        console.error("Supabase insert error:", insertError);
        return { success: false, error: insertError?.message || "Failed to insert article." };
      }
      savedRow = data as unknown as ArticleDbRow;
    }

    const articleItem = mapRowToArticle(savedRow);

    // Revalidate affected paths
    revalidatePath("/admin/articles");
    revalidatePath("/[locale]/blog", "page");
    revalidatePath(`/[locale]/blog/${cleanSlug}`, "page");

    return { success: true, article: articleItem };
  } catch (err: unknown) {
    return { success: false, error: (err as Error).message || "Failed to save article." };
  }
}

/**
 * Toggles status (e.g. quick publish/unpublish from table).
 */
export async function toggleArticleStatusAction(
  id: string,
  status: ArticleStatus
): Promise<{ success: boolean; error?: string }> {
  try {
    const adminId = await verifyAdminAuth();

    const supabase = await createClient();
    const updatePayload: Record<string, unknown> = {
      status,
      published_at: status === "published" ? new Date().toISOString() : null,
      created_by: adminId,
      // Note: updated_at is NOT passed; the database trigger updates updated_at automatically!
    };

    const { error } = await supabase
      .from("articles")
      .update(updatePayload)
      .eq("id", id);

    if (error) {
      console.error("Supabase toggleArticleStatusAction error:", error);
      return { success: false, error: error.message };
    }

    revalidatePath("/admin/articles");
    revalidatePath("/[locale]/blog", "page");

    return { success: true };
  } catch (err: unknown) {
    return { success: false, error: (err as Error).message || "Failed to update article status." };
  }
}

/**
 * Deletes an article by ID.
 */
export async function deleteArticleAction(
  id: string
): Promise<{ success: boolean; error?: string }> {
  try {
    await verifyAdminAuth();

    const supabase = await createClient();
    const { error } = await supabase.from("articles").delete().eq("id", id);

    if (error) {
      console.error("Supabase deleteArticleAction error:", error);
      return { success: false, error: error.message };
    }

    revalidatePath("/admin/articles");
    revalidatePath("/[locale]/blog", "page");

    return { success: true };
  } catch (err: unknown) {
    return { success: false, error: (err as Error).message || "Failed to delete article." };
  }
}
