import type { PageControlItem } from "./types";

/**
 * Master Page Inventory registry containing all public and platform routes
 * defined in the system architecture.
 */
export const MASTER_PAGE_INVENTORY: PageControlItem[] = [
  // ─── Marketing Family ──────────────────────────────────────────────────────
  {
    id: "home",
    path: "/",
    titleEn: "Home",
    titleAr: "الرئيسية",
    family: "marketing",
    status: "live",
    showInNavbar: true,
    showInFooter: true,
    isProtected: true,
    maintenanceNoticeEn: "Our home page is receiving routine system updates. Please check back shortly.",
    maintenanceNoticeAr: "الصفحة الرئيسية تخضع لعمليات تحديث دورية. يرجى العودة قريباً.",
  },
  {
    id: "about",
    path: "/about",
    titleEn: "About Musnad",
    titleAr: "عن مسند للتقنية",
    family: "marketing",
    status: "live",
    showInNavbar: true,
    showInFooter: true,
    isProtected: true,
    maintenanceNoticeEn: "We are currently updating our company profile and story.",
    maintenanceNoticeAr: "نقوم حالياً بتحديث الملف التعريفي وقصة الشركة.",
  },
  {
    id: "team",
    path: "/team",
    titleEn: "Team & Leadership",
    titleAr: "فريق العمل والقيادة",
    family: "marketing",
    status: "live",
    showInNavbar: true,
    showInFooter: true,
    maintenanceNoticeEn: "Our team roster is currently being refreshed.",
    maintenanceNoticeAr: "يتم تحديث قائمة فريق العمل حالياً.",
  },

  // ─── Services Family ──────────────────────────────────────────────────────
  {
    id: "services",
    path: "/services",
    titleEn: "Services Hub",
    titleAr: "نظرة عامة على الخدمات",
    family: "services",
    status: "live",
    showInNavbar: true,
    showInFooter: true,
    maintenanceNoticeEn: "Our capabilities catalog is undergoing maintenance.",
    maintenanceNoticeAr: "دليل الخدمات والقدرات يخضع للصيانة حالياً.",
  },
  {
    id: "service-product-engineering",
    path: "/services/product-engineering",
    titleEn: "Product Engineering",
    titleAr: "هندسة المنتجات",
    family: "services",
    status: "live",
    showInNavbar: false,
    showInFooter: false,
    maintenanceNoticeEn: "Product engineering specifications are being updated.",
    maintenanceNoticeAr: "يتم تحديث مواصفات هندسة المنتجات.",
  },
  {
    id: "service-platform-infrastructure",
    path: "/services/platform-infrastructure",
    titleEn: "Platform & Infrastructure",
    titleAr: "المنصات والبنية التحتية",
    family: "services",
    status: "live",
    showInNavbar: false,
    showInFooter: false,
    maintenanceNoticeEn: "Infrastructure solutions are undergoing documentation updates.",
    maintenanceNoticeAr: "حلول البنية التحتية تخضع لتحديث التوثيق.",
  },
  {
    id: "service-data-engineering",
    path: "/services/data-engineering",
    titleEn: "Data Engineering",
    titleAr: "هندسة البيانات",
    family: "services",
    status: "live",
    showInNavbar: false,
    showInFooter: false,
    maintenanceNoticeEn: "Data engineering service details are being updated.",
    maintenanceNoticeAr: "تفاصيل خدمات هندسة البيانات قيد التحديث.",
  },
  {
    id: "service-developer-tools",
    path: "/services/developer-tools",
    titleEn: "Developer Tools",
    titleAr: "أدوات المطورين",
    family: "services",
    status: "live",
    showInNavbar: false,
    showInFooter: false,
    maintenanceNoticeEn: "Developer tooling specifications are being updated.",
    maintenanceNoticeAr: "مواصفات أدوات المطورين قيد التحديث.",
  },
  {
    id: "service-ai-integration",
    path: "/services/ai-integration",
    titleEn: "AI Integration",
    titleAr: "تكامل الذكاء الاصطناعي",
    family: "services",
    status: "live",
    showInNavbar: false,
    showInFooter: false,
    maintenanceNoticeEn: "AI capabilities overview is being updated.",
    maintenanceNoticeAr: "نظرة عامة على قدرات الذكاء الاصطناعي قيد التحديث.",
  },
  {
    id: "service-design-engineering",
    path: "/services/design-engineering",
    titleEn: "Design Engineering",
    titleAr: "هندسة التصميم",
    family: "services",
    status: "live",
    showInNavbar: false,
    showInFooter: false,
    maintenanceNoticeEn: "Design engineering details are being updated.",
    maintenanceNoticeAr: "تفاصيل هندسة التصميم قيد التحديث.",
  },

  // ─── Projects Family ──────────────────────────────────────────────────────
  {
    id: "projects",
    path: "/projects",
    titleEn: "Projects Portfolio",
    titleAr: "محفظة المشاريع",
    family: "projects",
    status: "live",
    showInNavbar: true,
    showInFooter: true,
    maintenanceNoticeEn: "Our project showcase is being refreshed with new client deliverables.",
    maintenanceNoticeAr: "معرض المشاريع يخضع للتحديث بمشاريع جديدة.",
  },
  {
    id: "project-sahim-analytics",
    path: "/projects/sahim-analytics",
    titleEn: "Sahim Analytics",
    titleAr: "تحليلات سهم",
    family: "projects",
    status: "live",
    showInNavbar: false,
    showInFooter: false,
  },
  {
    id: "project-naft-deploy",
    path: "/projects/naft-deploy",
    titleEn: "Naft Deploy",
    titleAr: "نظام نفت ديبلوي",
    family: "projects",
    status: "live",
    showInNavbar: false,
    showInFooter: false,
  },
  {
    id: "project-rakeen-portal",
    path: "/projects/rakeen-portal",
    titleEn: "Rakeen Portal",
    titleAr: "بوابة ركين",
    family: "projects",
    status: "live",
    showInNavbar: false,
    showInFooter: false,
  },
  {
    id: "project-musnad-cli",
    path: "/projects/musnad-cli",
    titleEn: "Musnad CLI",
    titleAr: "أداة مسند للطرفية",
    family: "projects",
    status: "live",
    showInNavbar: false,
    showInFooter: false,
  },
  {
    id: "project-wathq-observability",
    path: "/projects/wathq-observability",
    titleEn: "Wathq Observability",
    titleAr: "منظومة وثق للرصد",
    family: "projects",
    status: "live",
    showInNavbar: false,
    showInFooter: false,
  },
  {
    id: "project-hudhud-chat",
    path: "/projects/hudhud-chat",
    titleEn: "Hudhud Chat",
    titleAr: "منصة هدهد للمحادثة",
    family: "projects",
    status: "live",
    showInNavbar: false,
    showInFooter: false,
  },

  // ─── Blog & Content Family ────────────────────────────────────────────────
  {
    id: "blog",
    path: "/blog",
    titleEn: "Technical Blog",
    titleAr: "المدونة التقنية",
    family: "blog",
    status: "live",
    showInNavbar: true,
    showInFooter: true,
    maintenanceNoticeEn: "Our engineering publication is undergoing maintenance.",
    maintenanceNoticeAr: "منصة التدوين الهندسي تخضع لأعمال الصيانة المجدولة.",
  },

  // ─── Careers Family ───────────────────────────────────────────────────────
  {
    id: "careers",
    path: "/careers",
    titleEn: "Careers & Jobs",
    titleAr: "الوظائف وفرص العمل",
    family: "careers",
    status: "live",
    showInNavbar: false,
    showInFooter: true,
    maintenanceNoticeEn: "Our job listings are being refreshed for the next hiring cycle.",
    maintenanceNoticeAr: "يتم تحديث قائمة الوظائف الشاغرة لدورة التوظيف القادمة.",
  },

  // ─── Support & Inquiries Family ───────────────────────────────────────────
  {
    id: "contact",
    path: "/contact",
    titleEn: "Contact & Consultations",
    titleAr: "تواصل معنا والاستشارات",
    family: "support",
    status: "live",
    showInNavbar: false,
    showInFooter: true,
    maintenanceNoticeEn: "Our contact desk is undergoing maintenance. Please reach out via email directly.",
    maintenanceNoticeAr: "بوابة التواصل تخضع للصيانة حالياً. يرجى التواصل عبر البريد الإلكتروني مباشرة.",
  },
  {
    id: "faq",
    path: "/faq",
    titleEn: "Frequently Asked Questions",
    titleAr: "الأسئلة الشائعة",
    family: "support",
    status: "live",
    showInNavbar: false,
    showInFooter: true,
    maintenanceNoticeEn: "FAQ knowledge base is being refreshed.",
    maintenanceNoticeAr: "قاعدة بيانات الأسئلة الشائعة قيد التحديث.",
  },

  // ─── Legal Family ─────────────────────────────────────────────────────────
  {
    id: "legal-privacy",
    path: "/legal/privacy-policy",
    titleEn: "Privacy Policy",
    titleAr: "سياسة الخصوصية",
    family: "legal",
    status: "live",
    showInNavbar: false,
    showInFooter: true,
  },
  {
    id: "legal-terms",
    path: "/legal/terms-of-service",
    titleEn: "Terms of Service",
    titleAr: "شروط الخدمة",
    family: "legal",
    status: "live",
    showInNavbar: false,
    showInFooter: true,
  },
  {
    id: "legal-cookies",
    path: "/legal/cookie-policy",
    titleEn: "Cookie Policy",
    titleAr: "سياسة ملفات تعريف الارتباط",
    family: "legal",
    status: "live",
    showInNavbar: false,
    showInFooter: true,
  },

  // ─── User Portal Family ───────────────────────────────────────────────────
  {
    id: "account",
    path: "/account",
    titleEn: "Account Portal",
    titleAr: "بوابة الحساب",
    family: "account",
    status: "live",
    showInNavbar: false,
    showInFooter: false,
    maintenanceNoticeEn: "Account services are temporarily undergoing scheduled system upgrades.",
    maintenanceNoticeAr: "خدمات الحساب تخضع لترقية دورية مجدولة للأنظمة.",
  },
];
