"use server";

import { auth } from "@clerk/nextjs/server";
import { revalidatePath } from "next/cache";
import { createClient } from "@/utils/supabase/server";
import type { TeamMember, TeamMemberFormData } from "./types";
import { DEFAULT_TEAM_MEMBERS } from "./fixtures";
import { getArticlesAction } from "@/lib/articles/actions";
import type { Article } from "@/lib/articles/types";

/**
 * Ensures caller has admin role.
 */
async function verifyAdminAuth(): Promise<string> {
  const { userId, sessionClaims } = await auth();

  if (!userId) {
    throw new Error("Unauthorized: Authentication required.");
  }

  const role = sessionClaims?.metadata?.role;
  if (role !== "admin") {
    throw new Error("Forbidden: Administrator privileges required.");
  }

  return userId;
}

interface TeamMemberDbRow {
  id: string;
  slug: string;
  name_en: string;
  name_ar: string;
  role_en: string;
  role_ar: string;
  bio_en: string | null;
  bio_ar: string | null;
  image: string | null;
  initials: string | null;
  department: string | null;
  skills: string[] | null;
  social_links: Record<string, string> | null;
  display_order: number;
  is_active: boolean;
  created_at: string;
  updated_at: string;
}

function mapRowToTeamMember(row: TeamMemberDbRow): TeamMember {
  return {
    id: row.id,
    slug: row.slug,
    nameEn: row.name_en,
    nameAr: row.name_ar,
    roleEn: row.role_en,
    roleAr: row.role_ar,
    bioEn: row.bio_en || "",
    bioAr: row.bio_ar || "",
    image: row.image || undefined,
    initials: row.initials || "SA",
    department: row.department || "Engineering",
    skills: row.skills || [],
    socialLinks: row.social_links || {},
    displayOrder: row.display_order ?? 0,
    isActive: row.is_active ?? true,
    createdAt: row.created_at,
    updatedAt: row.updated_at,
  };
}

/**
 * Retrieves team members from Supabase, with automatic fallback to defaults.
 */
export async function getTeamMembersAction(activeOnly: boolean = false): Promise<TeamMember[]> {
  try {
    const supabase = await createClient();
    let query = supabase
      .from("team_members")
      .select("*")
      .order("display_order", { ascending: true });

    if (activeOnly) {
      query = query.eq("is_active", true);
    }

    const { data, error } = await query;

    if (!error && data && data.length > 0) {
      return (data as unknown as TeamMemberDbRow[]).map(mapRowToTeamMember);
    }
  } catch (err) {
    console.warn("getTeamMembersAction fallback used:", err);
  }

  // Graceful fallback to default seed members
  return activeOnly
    ? DEFAULT_TEAM_MEMBERS.filter((m) => m.isActive)
    : DEFAULT_TEAM_MEMBERS;
}

/**
 * Retrieves a single team member by permanent URL slug.
 */
export async function getTeamMemberBySlugAction(slug: string): Promise<TeamMember | null> {
  const cleanSlug = slug.toLowerCase().trim();

  try {
    const supabase = await createClient();
    const { data, error } = await supabase
      .from("team_members")
      .select("*")
      .eq("slug", cleanSlug)
      .maybeSingle();

    if (!error && data) {
      return mapRowToTeamMember(data as unknown as TeamMemberDbRow);
    }
  } catch (err) {
    console.warn("getTeamMemberBySlugAction exception:", err);
  }

  // Fallback lookup
  const fallback = DEFAULT_TEAM_MEMBERS.find((m) => m.slug === cleanSlug);
  return fallback || null;
}

/**
 * Saves or updates a team member in Supabase.
 * Follows Supabase best practice: IDs and timestamps are generated by database defaults & triggers.
 */
export async function saveTeamMemberAction(
  formData: TeamMemberFormData
): Promise<{ success: boolean; member?: TeamMember; error?: string }> {
  try {
    await verifyAdminAuth();

    const cleanSlug = (formData.slug || formData.nameEn)
      .toLowerCase()
      .trim()
      .replace(/[^\w\s-]/g, "")
      .replace(/[\s_-]+/g, "-")
      .replace(/^-+|-+$/g, "");

    const initials =
      formData.initials ||
      formData.nameEn
        .trim()
        .split(/\s+/)
        .map((w) => w[0])
        .join("")
        .toUpperCase()
        .slice(0, 2) ||
      "SA";

    const baseRow = {
      slug: cleanSlug,
      name_en: formData.nameEn,
      name_ar: formData.nameAr,
      role_en: formData.roleEn,
      role_ar: formData.roleAr,
      bio_en: formData.bioEn || null,
      bio_ar: formData.bioAr || null,
      image: formData.image || null,
      initials,
      department: formData.department || "Engineering",
      skills: formData.skills || [],
      social_links: formData.socialLinks || {},
      display_order: formData.displayOrder ?? 0,
      is_active: formData.isActive ?? true,
    };

    const supabase = await createClient();
    let savedRow: TeamMemberDbRow;

    if (formData.id) {
      // UPDATE: Let trigger handle updated_at automatically
      const { data, error } = await supabase
        .from("team_members")
        .update(baseRow)
        .eq("id", formData.id)
        .select()
        .single();

      if (error || !data) {
        throw new Error(error?.message || "Failed to update team member.");
      }
      savedRow = data as unknown as TeamMemberDbRow;
    } else {
      // INSERT: Supabase generates id, created_at, and updated_at automatically
      const { data, error } = await supabase
        .from("team_members")
        .insert(baseRow)
        .select()
        .single();

      if (error || !data) {
        throw new Error(error?.message || "Failed to create team member.");
      }
      savedRow = data as unknown as TeamMemberDbRow;
    }

    const memberItem = mapRowToTeamMember(savedRow);

    // Revalidate paths
    revalidatePath("/admin/team");
    revalidatePath("/[locale]/team", "page");
    revalidatePath(`/[locale]/team/${cleanSlug}`, "page");

    return { success: true, member: memberItem };
  } catch (err: unknown) {
    return {
      success: false,
      error: (err as Error).message || "Failed to save team member.",
    };
  }
}

/**
 * Deletes a team member by ID.
 */
export async function deleteTeamMemberAction(
  id: string
): Promise<{ success: boolean; error?: string }> {
  try {
    await verifyAdminAuth();

    const supabase = await createClient();
    const { error } = await supabase.from("team_members").delete().eq("id", id);

    if (error) {
      throw new Error(error.message);
    }

    revalidatePath("/admin/team");
    revalidatePath("/[locale]/team", "page");

    return { success: true };
  } catch (err: unknown) {
    return {
      success: false,
      error: (err as Error).message || "Failed to delete team member.",
    };
  }
}

/**
 * Toggles a team member's active status.
 */
export async function toggleTeamMemberActiveAction(
  id: string,
  isActive: boolean
): Promise<{ success: boolean; error?: string }> {
  try {
    await verifyAdminAuth();

    const supabase = await createClient();
    const { error } = await supabase
      .from("team_members")
      .update({ is_active: isActive })
      .eq("id", id);

    if (error) {
      throw new Error(error.message);
    }

    revalidatePath("/admin/team");
    revalidatePath("/[locale]/team", "page");

    return { success: true };
  } catch (err: unknown) {
    return {
      success: false,
      error: (err as Error).message || "Failed to update member status.",
    };
  }
}

/**
 * Fetches all published articles authored by a given team member (matched by name or slug).
 */
export async function getArticlesByAuthorAction(
  authorNameOrSlug: string
): Promise<Article[]> {
  try {
    const allArticles = await getArticlesAction("published");
    const term = authorNameOrSlug.toLowerCase().trim();

    return allArticles.filter((art) => {
      const matchName = art.authorName.toLowerCase().includes(term);
      const matchSlug = art.authorName
        .toLowerCase()
        .replace(/\s+/g, "-")
        .includes(term);
      return matchName || matchSlug;
    });
  } catch {
    return [];
  }
}
