import type { TeamMember } from "./types";

export const DEFAULT_TEAM_MEMBERS: TeamMember[] = [
  {
    id: "shaher-alward",
    slug: "shaher-alward",
    nameEn: "Shaher Alward",
    nameAr: "شاهر الورد",
    roleEn: "Team Lead / Product Lead",
    roleAr: "قائد الفريق / قائد المنتجات",
    bioEn: "Team Lead and Product Lead at Musnad Tech with deep focus on product strategy and software engineering leadership.",
    bioAr: "قائد الفريق وقائد المنتجات في مسند للتقنية مع تركيز عميق على استراتيجية المنتجات والقيادة الهندسية.",
    initials: "SA",
    department: "Leadership",
    skills: ["Product Leadership", "Product Strategy", "System Architecture"],
    socialLinks: {
      linkedin: "https://linkedin.com",
      x: "https://x.com",
    },
    displayOrder: 1,
    isActive: true,
    createdAt: "2026-01-01T00:00:00Z",
    updatedAt: "2026-01-01T00:00:00Z",
  },
  {
    id: "sabri-alshaibani",
    slug: "sabri-alshaibani",
    nameEn: "Sabri Alshaibani",
    nameAr: "صبري الشيباني",
    roleEn: "Engineering / Technical Lead",
    roleAr: "القائد الهندسي / التقني",
    bioEn: "Engineering and Technical Lead at Musnad Tech specializing in distributed systems, modern web platforms, and cloud architecture.",
    bioAr: "القائد الهندسي والتقني في مسند للتقنية، متخصص في الأنظمة الموزعة، منصات الويب الحديثة، والمعمارية السحابية.",
    initials: "SS",
    department: "Engineering",
    skills: ["Technical Leadership", "Cloud Architecture", "Next.js", "PostgreSQL"],
    socialLinks: {
      github: "https://github.com",
      linkedin: "https://linkedin.com",
      x: "https://x.com",
    },
    displayOrder: 2,
    isActive: true,
    createdAt: "2026-01-01T00:00:00Z",
    updatedAt: "2026-01-01T00:00:00Z",
  },
  {
    id: "islam-adel",
    slug: "islam-adel",
    nameEn: "Islam Adel",
    nameAr: "إسلام عادل",
    roleEn: "Software Engineer / Frontend Lead",
    roleAr: "مهندس برمجيات / قائد الواجهات",
    bioEn: "Software Engineer and Frontend Lead at Musnad Tech driving responsive, accessible, and high-performance user interfaces.",
    bioAr: "مهندس برمجيات وقائد الواجهات في مسند للتقنية، يقود تطوير واجهات مستخدم عالية الأداء، متجاوبة وشاملة.",
    initials: "IA",
    department: "Engineering",
    skills: ["Software Engineering", "Frontend Architecture", "Design Systems", "TypeScript"],
    socialLinks: {
      github: "https://github.com",
      linkedin: "https://linkedin.com",
    },
    displayOrder: 3,
    isActive: true,
    createdAt: "2026-01-01T00:00:00Z",
    updatedAt: "2026-01-01T00:00:00Z",
  },
];
